### ISSUE TITLE
"Should app be exposed to anonymous visitors?" prompt is potentially confusing.

### ISSUE THREAD

**Issue by lightnin** [YunoHost-Apps/adguardhome_ynh#31]
When I encounter this option in the install dialog, I wonder the following:

1. Does the DNS service need this setting to be [true] in order to respond to [anonymous?] requests from machines on the local network?
2. Or does this refer only to the web interface for adguard? If so, my preference would be to not make the web interface visible to anonymous users. And I would ask: Is there any known use case in which it would be advantageous to show the web interface to anonymous (i.e. not logged into yunohost) users? Or would it be better to set this option to false for all installs, and hide the UX option completely?

**Comment by kay0u** [comment]
This option corresponds to your second possibility, that's a good point.

I think that we can indeed remove this option, the best possibility would be to consider all the users who have access to this admin page as administrator, by making sure that we cannot add "visitors" there. Because for now only one person will be able to log in, the one presented as the administrator of adguardhome.

But maybe there are people who want external accounts to YNH to manage this app?

For now, I'll at least remove the `is_public` argument which doesn't make sense
